# -*- coding: utf-8 -*-
"""youtube_audio_speech recognition .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f0YMCdjdofjRfruGxAeinIXeFLj5Gxle

# **Youtube audio extractor**
"""

#create a Python code that extracts audio from YouTube videos, converts it to text, and stores it in a txt file.

"""Import packages

1. Validator to ensure URL is for YouTube videos.
"""

#pip install re

import re

def is_youtube_url(url: str) -> bool:
    """
    Validates if a given URL is a YouTube video URL.
    """
    youtube_regex = (
        r"(https?://)?(www\.)?"  # Optional http(s):// or www.
        r"(youtube\.com|youtu\.be)/"  # youtube.com or youtu.be
        r"(watch\?v=|embed/|v/|)([\w-]{11})"  # Video ID part
    )
    match = re.match(youtube_regex, url)
    return bool(match)

# Example usage:
# print(is_youtube_url("https://www.youtube.com/watch?v=dQw4w9WgXcQ"))  # True
# print(is_youtube_url("https://youtu.be/dQw4w9WgXcQ"))  # True
# print(is_youtube_url("http://youtube.com/watch?v=dQw4w9WgXcQ"))  # True
# print(is_youtube_url("https://www.google.com"))  # False

"""Example to show validator functions as intended."""

print(is_youtube_url("https://www.youtube.com/watch?v=dQw4w9WgXcQ")) # True
print(is_youtube_url("https://www.google.com"))  # False

"""2. To get user to input youtube url or exit, with loop and validator of user input"""

def main():
    """Main function to run the YouTube audio extractor."""
    print("=" * 80)
    print("YouTube Audio Extractor - Convert Video Audio to Text")
    print("=" * 80 + "\n")

    #extractor = YouTubeAudioExtractor(output_dir="youtube_audio")

    while True:
        print("\nOptions:")
        print("1. Process a YouTube video")
        #print("2. Display results")
        #print("3. Save results to CSV")
        print("4. Exit")

        choice = input("\nEnter your choice (1-4): ").strip()

        if choice == "1":
            youtube_url = input("Enter YouTube URL: ").strip()

            if not is_youtube_url(youtube_url):
                print("✗ Invalid URL. Please try again.")
                continue
        elif choice == "4":
            print("✓ Exiting...")
            break

        else:
            print("✗ Invalid choice. Please try again.")

"""3. Download audio from youtube link"""

pip install pytubefix

from pytubefix import YouTube
import os

def download_audio_pytubefix(url, destination='./'):
    """
    Downloads the audio stream from a YouTube video using pytubefix and saves it as an MP3.
    """
    try:
        yt = YouTube(url)
        # Filter for the best audio stream
        audio_stream = yt.streams.get_audio_only()

        print(f"Downloading audio for: {yt.title}...")

        # Download the file
        out_file = audio_stream.download(output_path=destination)

        # Rename the file to have an .mp3 extension
        base, ext = os.path.splitext(out_file)
        new_file = base + '.mp3'
        os.rename(out_file, new_file)

        print(f"Successfully downloaded: {os.path.basename(new_file)}")
        return new_file # Return the full path as a string

    except Exception as e:
        print(f"An error occurred: {e}")

# Example usage:
#1
video_url = "https://www.youtube.com/watch?v=q5Q7h0HB5JQ" # FOMC Jan-28-2026 meeting (Federal Open Markets Committee)
downloaded_audio_file = download_audio_pytubefix(video_url)

# Example usage:
#2
video_url = "https://www.youtube.com/watch?v=KckGHaBLSn4" # Statement by Federal Reserve Chair
downloaded_audio_file_2 = download_audio_pytubefix(video_url)

# Example usage:
#3
video_url = "https://www.youtube.com/watch?v=lp1sJDa5MsI" # Example 3 small clip
downloaded_audio_file_3 = download_audio_pytubefix(video_url)

"""4. Speech recognition"""

pip install --upgrade pip

# !pip install speech_recognition - doesn't work because yt_dlp is a prerequisite

!pip install yt_dlp

!pip install google.cloud

from yt_dlp import YoutubeDL
from google.cloud import speech_v1

from pydub import AudioSegment

#!apt-get -qq install -y speech_recognition
#E: Unable to locate package speech_recognition

#!pip install speech_recognition
#ERROR: Could not find a version that satisfies the requirement speech_recognition (from versions: none)
#ERROR: No matching distribution found for speech_recognition

!pip install SpeechRecognition
import speech_recognition as sr
print(f"SpeechRecognition version: {sr.__version__}")

#import speech_recognition as sr #repeated from above

#from yt_dlp import YoutubeDL #repeated from above
#from google.cloud import speech_v1 #repeated from above
#import speech_recognition as sr #repeated from above
#from pydub import AudioSegment #repeated from above

pip install -U openai-whisper

print(downloaded_audio_file_3)

import whisper

# 1. Load the model (tiny, base, small, medium, large)
# "base" is a good balance of speed and accuracy
model = whisper.load_model("base")

# 2. Transcribe the audio file
# Whisper directly supports mp3, mp4, wav, m4a, etc.
audio_file_path = "/content/Chair Powell’s Birthday Message for Chairman Greenspan, March 6, 2026.mp3"
result = model.transcribe(audio_file_path)

# 3. Print or save the transcribed text
print(result["text"])
# Optionally, save to a file
with open("transcription.txt", "w") as f:
    f.write(result["text"])

#######################################

"""

#Reference code v1

import os
from pathlib import Path
from typing import Optional
import pandas as pd
from yt_dlp import YoutubeDL
from google.cloud import speech_v1
import speech_recognition as sr
from pydub import AudioSegment
# Note: 're' is already imported in RzFsbDSKLjsW if clean_transcriptions is used

class YouTubeAudioExtractor:
    """#Extract audio from YouTube videos and convert to text.""" """
"""
    def __init__(self, output_dir: str = "youtube_audio"):
        """
        #Initialize the extractor.

        #Args:
            #output_dir: Directory to store downloaded audio files
"""
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(exist_ok=True)
        self.df = pd.DataFrame(columns=["youtube_url", "video_title", "audio_file", "transcription"])

    def download_audio(self, youtube_url: str) -> Optional[str]:
        """
        #Download audio from YouTube video.

        #Args:
            #youtube_url: URL of the YouTube video

        #Returns:
            #Path to the downloaded audio file, or None if failed
"""
        try:
            print(f"Downloading audio from: {youtube_url}")

            ydl_opts = {
                "format": "bestaudio/best",
                "postprocessors": [
                    {
                        "key": "FFmpegExtractAudio",
                        "preferredcodec": "mp3",
                        "preferredquality": "192",
                    }
                ],
                "outtmpl": str(self.output_dir / "%(title)s"),
                "quiet": False,
                "no_warnings": False,
            }

            with YoutubeDL(ydl_opts) as ydl:
                info = ydl.extract_info(youtube_url, download=True)
                # Fix for filename potentially having problematic characters or being too long
                # Use original title for info, but sanitize for filename
                sanitized_title = info['title'].replace('/', '_').replace('\\', '_').replace(':', '_')
                audio_file = f"{self.output_dir / sanitized_title}.mp3"

            print(f"✓ Audio downloaded successfully: {audio_file}")
            return audio_file

        except Exception as e:
            print(f"✗ Error downloading audio: {e}")
            return None

    def transcribe_audio_google(self, audio_file: str) -> Optional[str]:
"""
        #Transcribe audio using Google Cloud Speech-to-Text API.

        #Args:
            #audio_file: Path to the audio file

        #Returns:
            #Transcribed text, or None if failed
"""
        try:
            print(f"Transcribing audio: {audio_file}")

            # Initialize Google Speech client
            client = speech_v1.SpeechClient()

            # Read audio file
            with open(audio_file, "rb") as f:
                audio_content = f.read()

            audio = speech_v1.RecognitionAudio(content=audio_content)

            config = speech_v1.RecognitionConfig(
                encoding=speech_v1.RecognitionConfig.AudioEncoding.MP3,
                sample_rate_hertz=44100,
                language_code="en-US",
            )

            # Use long_running_recognize for longer audio files
            operation = client.long_running_recognize(config=config, audio=audio)
            response = operation.result(timeout=3600)  # Wait up to 1 hour

            transcription = ""
            for result in response.results:
                if result.alternatives:
                    transcription += result.alternatives[0].transcript + " "

            print(f"✓ Transcription completed")
            return transcription.strip()

        except Exception as e:
            print(f"✗ Error transcribing audio: {e}")
            return None

    def transcribe_audio_local(self, audio_file: str) -> Optional[str]:
"""
        #Alternative: Transcribe using SpeechRecognition library (free, no API key needed).

        #Args:
            #audio_file: Path to the audio file

        #Returns:
            #Transcribed text, or None if failed
"""
        try:
            # sr imported at the top of the cell

            print(f"Transcribing audio using local recognizer: {audio_file}")

            recognizer = sr.Recognizer()

            # Convert MP3 to WAV for SpeechRecognition
            sound = AudioSegment.from_mp3(audio_file)
            wav_file = audio_file.replace(".mp3", ".wav")
            sound.export(wav_file, format="wav")

            with sr.AudioFile(wav_file) as source:
                audio_data = recognizer.record(source)

            try:
                text = recognizer.recognize_google(audio_data)
                print(f"✓ Transcription completed")
                return text
            except sr.UnknownValueError:
                print("✗ Could not understand audio")
                return None
            except sr.RequestError as e:
                print(f"✗ API error: {e}")
                return None
            finally:
                # Clean up the temporary WAV file
                if os.path.exists(wav_file):
                    os.remove(wav_file)

        except Exception as e:
            print(f"✗ Error transcribing audio: {e}")
            return None

    def process_video(self, youtube_url: str, use_google_api: bool = False) -> bool:
"""
        #Process a YouTube video: download audio and transcribe.

        #Args:
            #youtube_url: URL of the YouTube video
            #use_google_api: If True, use Google Cloud API; otherwise use local recognizer

        #Returns:
            #True if successful, False otherwise
"""
        try:
            # Step 1: Download audio
            audio_file = self.download_audio(youtube_url)
            if not audio_file:
                return False

            # Step 2: Extract video title
            ydl_opts = {"quiet": True, "no_warnings": True}
            with YoutubeDL(ydl_opts) as ydl:
                info = ydl.extract_info(youtube_url, download=False)
                video_title = info.get("title", "Unknown")

            # Step 3: Transcribe audio
            if use_google_api:
                transcription = self.transcribe_audio_google(audio_file)
            else:
                transcription = self.transcribe_audio_local(audio_file)

            if not transcription:
                return False

            # Step 4: Store in dataframe
            new_row = pd.DataFrame(
                {
                    "youtube_url": [youtube_url],
                    "video_title": [video_title],
                    "audio_file": [audio_file],
                    "transcription": [transcription],
                }
            )
            self.df = pd.concat([self.df, new_row], ignore_index=True)

            print(f"✓ Successfully processed: {video_title}\n")
            return True

        except Exception as e:
            print(f"✗ Error processing video: {e}\n")
            return False

    def save_dataframe(self, output_file: str = "transcriptions.csv") -> None:
"""
        #Save the dataframe to a CSV file.

        #Args:
            #output_file: Output file path
"""
        try:
            self.df.to_csv(output_file, index=False, encoding="utf-8")
            print(f"✓ Dataframe saved to: {output_file}")
        except Exception as e:
            print(f"✗ Error saving dataframe: {e}")

    def display_results(self) -> None:
"""#Display the dataframe with results."""
        #if self.df.empty:
            #print("No results to display.")
        #else:
            #print("\n" + "=" * 80)
            #print("TRANSCRIPTION RESULTS")
            #print("=" * 80)
            #print(self.df.to_string())
            #print("=" * 80 + "\n")


# Removed the main() function call here to prevent automatic execution when defining the class.